# Site settings
# YAML cheat sheet: https://quickref.me/yaml

title: "Eleventy Sveltia CMS Starter"
description: "A template for building a fast Eleventy blog with Sveltia CMS, for deployment to Netlify"
url: "https://eleventy-sveltia-cms-starter.netlify.app"